FROM debian:bookworm-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/share/vox/web /var/cache/vox /var/lib/vox

COPY vox-${TARGETARCH} /usr/local/bin/vox
COPY web /usr/share/vox/web

WORKDIR /var/lib/vox

EXPOSE 5050

ENTRYPOINT ["vox"]
CMD ["-f"]
